
test: api-session/type/type.go
	go build ./...
	go test -cover ./...
	cd ./pkg/api-strategy/ && go test -cover ./...
	cd ./pkg/global-api-strategy/ && go test -cover ./...

api-session/type/type.go:
	mockgen github.com/pefish/go-core/api-session/type IApiSession > mock/mock-api-session/mock.go
	mockgen github.com/pefish/go-core/api-session/type IApiSession > pkg/api-strategy/mock/mock-api-session/mock.go
